#!/bin/bash

set -Eeuo pipefail

DEFAULT_REF="refs/_local-ignored"
REF="${GIT_IGNORE_REF:-$DEFAULT_REF}"

usage() {
    cat <<EOF
Usage: git-ignore-local <command> [args]

Commands:
    push           Capture current state to ignore
    reset       Delete captured state to ignore
    ls                  List files in the local ignore list
    diff [<opt>] [--] [<local-ignored files>...]
                        Show diff between original and worktree files
    filter-clean        Filter for staging (used in gitconfig)
    filter-smudge       Filter for checkout (used in gitconfig)
    help                Show this help message

Environment variables:
    GIT_IGNORE_REF      ref for storing backup files
                           (default: $DEFAULT_REF)
EOF
}

_print() {
    echo "$@" >&2
}

filter_clean() {
    if ! git show-ref --verify -q "$REF" ; then
        cat
        exit 0
    fi

    local path="$1"

    local current=$(git hash-object -w --stdin)
    local captured=$(git rev-parse "$REF:$path")
    local original=$(git rev-parse "${REF}^1:$path")

    set +Ee
    git merge-file --object-id -p \
        -L local -L ignored -L original \
        "$current" "$captured" "$original"
    local status="$?"
    set -Ee

    if [[ $status -gt 0 ]] ; then
        _print "WARN: Conflicts found in local-ignored files and worktree - manual resolution required"
    fi
}

filter_smudge() {
    if ! git show-ref --verify -q "$REF" ; then
        cat
        exit 0
    fi

    local path="$1"

    local captured=$(git rev-parse "$REF:$path")
    local original=$(git rev-parse "${REF}^1:$path")

    local current=$(git hash-object -w --stdin)

    set +Ee
    git merge-file --object-id -p \
        -L local -L ignored -L original \
        "$captured" "$original" "$current"
    local status="$?"
    set -Ee

    if [[ $status -gt 0 ]] ; then
        _print "WARN: local-ignored files conflict with worktree changes; the smudge filter generated conflicting content - manual resolution required"
    fi
}

_push() {
    local captured=$(git stash create "local-ignored captured on $(git rev-parse --abbrev-ref HEAD)")

    git update-ref --create-reflog "$REF" "$captured"
    echo $captured
}

_reset() {
    if ! git show-ref --verify -q "$REF" ; then
        _print "No files ignored locally"
    fi
    local hash=$(git rev-parse "$REF")
    git update-ref -d "$REF"

    _print "Forget captured state: $hash"
}

list_files() {
    if ! git show-ref --verify -q "$REF" ; then
        _print "No local-ignored entries."
        exit 0
    fi

    git diff --name-only "$REF"^- "$@"

    _print
    _print "Info: you need to set 'filter' on gitattributes(5) for ignoreing these files."

}

_diff() {
    if ! git show-ref --verify -q "$REF" ; then
        _print "No local-ignored entries."
        exit 0
    fi

    git diff "$REF" "$@"
}

main() {
    if [ $# -eq 0 ]; then
        usage
        exit 1
    fi

    local command="$1"
    shift

    case "$command" in
        push)
            _push "$@"
            ;;
        reset)
            _reset "$@"
            ;;
        ls)
            list_files "$@"
            ;;
        diff)
            _diff "$@"
            ;;
        filter-clean)
            # specify '%f' in git config
            filter_clean "$@"
            ;;
        filter-smudge)
            # specify '%f' in git config
            filter_smudge "$@"
            ;;
        help|-h|--help)
            usage
            ;;
        *)
            echo "Error: Unknown command '$command'" >&2
            usage
            exit 1
            ;;
    esac
}

main "$@"
